USE [xxDBxx]
GO

/****** Object:  View [dbo].[VW_Validacion_SERVIDOR_UNO]    ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_Validacion_SERVIDOR_UNO]
AS
SELECT 
CASE WHEN	VALIDAR_TABLA IN ('Ok','No Aplica') AND 
			VALIDAR_MONTO IN ('Ok','No Aplica') AND
			VALIDAR_FECHA IN ('Ok','No Aplica') THEN 'EXITOSA'
			ELSE 'ERRADA' END AS MIGRACION
,MIGRA.*
FROM 
	(
		SELECT 
		ISNULL(A.TABLA,B.TABLA) TABLA
		,A.CANT REGISTROS_MX
		,B.CANT REGISTROS_IRPA
		,CASE WHEN A.CANT IS NULL THEN 'tabla no disponible en SERVIDOR_UNO'
			  WHEN B.CANT IS NULL THEN 'tabla no disponible en SERVIDOR_DOS'
			  WHEN A.CANT=B.CANT THEN 'Ok' 
								 ELSE 'Diferencias - Validar'
		END AS VALIDAR_TABLA

		,REPLACE(A.MONTO,',','.') MONTOS_MX
		,REPLACE(B.MONTO,',','.') MONTOS_IRPA
		,CASE 
			WHEN 
			A.TABLA IN 
			(
			'SISCEL.CO_CARTERA',
			'SISCEL.CO_CANCELADOS',
			'SISCEL.CO_PAGOS',
			'SISCEL.CO_PAGOSCONC',
			'SISCEL.GE_CARGOS',
			'SISCEL.FA_HISTDOCU',
			'TOL.TOL_TRAFCIERR_TO_330722',
			'TOL.TOL_TRAFCIERR_TO_18180722',
			'TOL.TOL_TRAFCIERR_TO_22220722'
			) THEN
		 CASE WHEN A.MONTO IS NULL THEN 'tabla no disponible en Mexico'
			  WHEN B.MONTO IS NULL THEN 'tabla no disponible en Iridium'
			  WHEN A.MONTO=B.MONTO THEN 'Ok' 
								 ELSE 'Diferencias - Validar'
		END ELSE 'No Aplica' END AS VALIDAR_MONTO

		,A.FECHA FECHA_MX
		,B.FECHA FECHA_IRPA
		,CASE 
			WHEN 
			A.TABLA IN 
			(
			'SISCEL.GA_ABOCEL',
			'SISCEL.GE_CLIENTES',
			'SISCEL.CO_CARTERA',
			'SISCEL.CO_CANCELADOS',
			'SISCEL.CO_PAGOS',
			'SISCEL.CO_PAGOSCONC',
			'SISCEL.GE_CARGOS',
			'SISCEL.FA_HISTDOCU',
			'TOL.TOL_TRAFCIERR_TO_330722',
			'TOL.TOL_TRAFCIERR_TO_18180722',
			'TOL.TOL_TRAFCIERR_TO_22220722'
			) THEN
		 CASE WHEN A.FECHA IS NULL THEN 'tabla no disponible en Mexico'
			  WHEN B.FECHA IS NULL THEN 'tabla no disponible en Iridium'
			  WHEN A.FECHA=B.FECHA THEN 'Ok' 
								 ELSE 'Diferencias - Validar'
		END ELSE 'No Aplica' END AS VALIDAR_FECHA

		FROM 
						(
							SELECT TABLA,CANT,MONTO,FECHA 
							FROM MASTER.DBO.SCL_VALIDACION_RAO
							WHERE SERVIDOR in ('SERVIDOR_UNO')
						) A 
		FULL OUTER JOIN 
						(
							SELECT TABLA,CANT,MONTO,FECHA 
							FROM MASTER.DBO.SCL_VALIDACION_RAO
							WHERE SERVIDOR in ('SERVIDOR_DOS')
						) B ON A.TABLA = B.TABLA
	) MIGRA LEFT JOIN MASTER.DBO.SCL_HISTORICAS_RAO HIST ON MIGRA.TABLA = HIST.TABLA
GO


